{
 "title": "up_ws监控",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds",
     "legendFormat": "Target Interval Length"
    },
    {
     "expr": "prometheus_target_metadata_cache_bytes",
     "legendFormat": "Target Metadata Cache Bytes"
    },
    {
     "expr": "prometheus_target_metadata_cache_entries",
     "legendFormat": "Target Metadata Cache Entries"
    },
    {
     "expr": "prometheus_target_scrape_pool_exceeded_label_limits_total",
     "legendFormat": "Target Scrape Pool Exceeded Label Limits"
    },
    {
     "expr": "prometheus_target_scrape_pool_exceeded_target_limit_total",
     "legendFormat": "Target Scrape Pool Exceeded Target Limit"
    },
    {
     "expr": "prometheus_target_scrape_pool_reloads_failed_total",
     "legendFormat": "Target Scrape Pool Reloads Failed"
    },
    {
     "expr": "prometheus_target_scrape_pool_reloads_total",
     "legendFormat": "Target Scrape Pool Reloads Total"
    },
    {
     "expr": "prometheus_target_scrape_pool_symboltable_items",
     "legendFormat": "Target Scrape Pool Symboltable Items"
    },
    {
     "expr": "prometheus_target_scrape_pool_sync_total",
     "legendFormat": "Target Scrape Pool Sync Total"
    },
    {
     "expr": "prometheus_target_scrape_pool_target_limit",
     "legendFormat": "Target Scrape Pool Target Limit"
    },
    {
     "expr": "prometheus_target_scrape_pool_targets",
     "legendFormat": "Target Scrape Pool Targets"
    },
    {
     "expr": "prometheus_target_scrape_pools_failed_total",
     "legendFormat": "Target Scrape Pools Failed"
    },
    {
     "expr": "prometheus_target_scrape_pools_total",
     "legendFormat": "Target Scrape Pools Total"
    },
    {
     "expr": "prometheus_target_scrapes_cache_flush_forced_total",
     "legendFormat": "Target Scrapes Cache Flush Forced"
    },
    {
     "expr": "prometheus_target_scrapes_exceeded_body_size_limit_total",
     "legendFormat": "Target Scrapes Exceeded Body Size Limit"
    },
    {
     "expr": "prometheus_target_scrapes_exceeded_native_histogram_bucket_limit_total",
     "legendFormat": "Target Scrapes Exceeded Native Histogram Bucket Limit"
    },
    {
     "expr": "prometheus_target_scrapes_exceeded_sample_limit_total",
     "legendFormat": "Target Scrapes Exceeded Sample Limit"
    },
    {
     "expr": "prometheus_target_scrapes_exemplar_out_of_order_total",
     "legendFormat": "Target Scrapes Exemplar Out of Order"
    },
    {
     "expr": "prometheus_target_scrapes_sample_duplicate_timestamp_total",
     "legendFormat": "Target Scrapes Sample Duplicate Timestamp"
    },
    {
     "expr": "prometheus_target_scrapes_sample_out_of_bounds_total",
     "legendFormat": "Target Scrapes Sample Out of Bounds"
    },
    {
     "expr": "prometheus_target_scrapes_sample_out_of_order_total",
     "legendFormat": "Target Scrapes Sample Out of Order"
    },
    {
     "expr": "prometheus_target_sync_failed_total",
     "legendFormat": "Target Sync Failed"
    },
    {
     "expr": "prometheus_target_sync_length_seconds",
     "legendFormat": "Target Sync Length"
    }
   ]
  },
  {
   "title": "rule监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds",
     "legendFormat": "Rule Evaluation Duration"
    },
    {
     "expr": "prometheus_rule_group_duration_seconds",
     "legendFormat": "Rule Group Duration"
    }
   ]
  },
  {
   "title": "ds监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "prometheus_sd_azure_cache_hit_total",
     "legendFormat": "SD Azure Cache Hit Total"
    },
    {
     "expr": "prometheus_sd_azure_failures_total",
     "legendFormat": "SD Azure Failures Total"
    },
    {
     "expr": "prometheus_sd_consul_rpc_duration_seconds",
     "legendFormat": "SD Consul RPC Duration"
    },
    {
     "expr": "prometheus_sd_consul_rpc_failures_total",
     "legendFormat": "SD Consul RPC Failures"
    },
    {
     "expr": "prometheus_sd_discovered_targets",
     "legendFormat": "SD Discovered Targets"
    },
    {
     "expr": "prometheus_sd_dns_lookup_failures_total",
     "legendFormat": "SD DNS Lookup Failures"
    },
    {
     "expr": "prometheus_sd_dns_lookups_total",
     "legendFormat": "SD DNS Lookups Total"
    },
    { "expr": "prometheus_sd_failed_configs", "legendFormat": "SD Failed Configs" },
    {
     "expr": "prometheus_sd_file_read_errors_total",
     "legendFormat": "SD File Read Errors"
    },
    {
     "expr": "prometheus_sd_file_scan_duration_seconds",
     "legendFormat": "SD File Scan Duration"
    },
    {
     "expr": "prometheus_sd_file_watcher_errors_total",
     "legendFormat": "SD File Watcher Errors"
    },
    {
     "expr": "prometheus_sd_http_failures_total",
     "legendFormat": "SD HTTP Failures Total"
    },
    {
     "expr": "prometheus_sd_kubernetes_events_total",
     "legendFormat": "SD Kubernetes Events"
    },
    {
     "expr": "prometheus_sd_kubernetes_failures_total",
     "legendFormat": "SD Kubernetes Failures"
    },
    {
     "expr": "prometheus_sd_kuma_fetch_duration_seconds",
     "legendFormat": "SD Kuma Fetch Duration"
    },
    {
     "expr": "prometheus_sd_kuma_fetch_failures_total",
     "legendFormat": "SD Kuma Fetch Failures"
    },
    {
     "expr": "prometheus_sd_kuma_fetch_skipped_updates_total",
     "legendFormat": "SD Kuma Fetch Skipped Updates"
    },
    {
     "expr": "prometheus_sd_linode_failures_total",
     "legendFormat": "SD Linode Failures Total"
    },
    {
     "expr": "prometheus_sd_nomad_failures_total",
     "legendFormat": "SD Nomad Failures Total"
    },
    {
     "expr": "prometheus_sd_received_updates_total",
     "legendFormat": "SD Received Updates Total"
    },
    {
     "expr": "prometheus_sd_updates_delayed_total",
     "legendFormat": "SD Updates Delayed Total"
    },
    { "expr": "prometheus_sd_updates_total", "legendFormat": "SD Updates Total" }
   ]
  },
  {
   "title": "remote监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "prometheus_remote_read_handler_queries",
     "legendFormat": "Remote Read Handler Queries"
    },
    {
     "expr": "prometheus_remote_storage_exemplars_in_total",
     "legendFormat": "Remote Storage Exemplars In Total"
    },
    {
     "expr": "prometheus_remote_storage_highest_timestamp_in_seconds",
     "legendFormat": "Remote Storage Highest Timestamp"
    },
    {
     "expr": "prometheus_remote_storage_histograms_in_total",
     "legendFormat": "Remote Storage Histograms In Total"
    },
    {
     "expr": "prometheus_remote_storage_samples_in_total",
     "legendFormat": "Remote Storage Samples In Total"
    },
    {
     "expr": "prometheus_remote_storage_string_interner_zero_reference_releases_total",
     "legendFormat": "Remote Storage String Interner Releases"
    }
   ]
  },
  {
   "title": "process监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "CPU Seconds Total" },
    { "expr": "process_cpu_usage", "legendFormat": "CPU Usage" },
    { "expr": "process_files_max_files", "legendFormat": "Max Files" },
    { "expr": "process_files_open_files", "legendFormat": "Open Files" },
    { "expr": "process_max_fds", "legendFormat": "Max File Descriptors" },
    {
     "expr": "process_network_receive_bytes_total",
     "legendFormat": "Network Received Bytes"
    },
    {
     "expr": "process_network_transmit_bytes_total",
     "legendFormat": "Network Transmitted Bytes"
    },
    { "expr": "process_open_fds", "legendFormat": "Open File Descriptors" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident Memory Bytes" },
    { "expr": "process_start_time_seconds", "legendFormat": "Start Time Seconds" },
    { "expr": "process_uptime_seconds", "legendFormat": "Uptime Seconds" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual Memory Bytes" },
    {
     "expr": "process_virtual_memory_max_bytes",
     "legendFormat": "Max Virtual Memory Bytes"
    }
   ]
  },
  {
   "title": "net_conntrack监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_attempted_total",
     "legendFormat": "Dialer Connection Attempts"
    },
    {
     "expr": "net_conntrack_dialer_conn_closed_total",
     "legendFormat": "Dialer Closed Connections"
    },
    {
     "expr": "net_conntrack_dialer_conn_established_total",
     "legendFormat": "Dialer Established Connections"
    },
    {
     "expr": "net_conntrack_dialer_conn_failed_total",
     "legendFormat": "Dialer Failed Connections"
    },
    {
     "expr": "net_conntrack_listener_conn_accepted_total",
     "legendFormat": "Listener Accepted Connections"
    },
    {
     "expr": "net_conntrack_listener_conn_closed_total",
     "legendFormat": "Listener Closed Connections"
    }
   ]
  },
  {
   "title": "http_server监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "http_server_requests_seconds", "legendFormat": "{{__name__}}" },
    {
     "expr": "http_server_requests_seconds_max",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "go_sched监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "go_sched_gomaxprocs_threads", "legendFormat": "{{__name__}}" },
    { "expr": "go_sched_goroutines_goroutines", "legendFormat": "{{__name__}}" },
    { "expr": "go_sched_latencies_seconds", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_sched_pauses_stopping_gc_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_sched_pauses_stopping_other_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_sched_pauses_total_gc_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_sched_pauses_total_other_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "ds_tsak监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "ds_task_execution_count", "legendFormat": "{{__name__}}" },
    {
     "expr": "ds_task_execution_duration_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ds_task_execution_duration_seconds_max",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "go_memstats监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_alloc_bytes_total", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_memstats_buck_hash_sys_bytes",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "go_memstats_frees_total", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_gc_sys_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_heap_objects", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_memstats_last_gc_time_seconds",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "go_memstats_mallocs_total", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_mcache_inuse_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_mcache_sys_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_mspan_inuse_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_mspan_sys_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_other_sys_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_stack_sys_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_sys_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "go_gc监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "go_gc_cycles_automatic_gc_cycles_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_gc_cycles_forced_gc_cycles_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_gc_cycles_total_gc_cycles_total",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_gogc_percent", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_gomemlimit_bytes", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_gc_heap_allocs_by_size_bytes",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "go_gc_heap_allocs_bytes_total", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_gc_heap_allocs_objects_total",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "go_gc_heap_frees_by_size_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_heap_frees_bytes_total", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_heap_frees_objects_total", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_heap_goal_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_heap_live_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_heap_objects_objects", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_gc_heap_tiny_allocs_objects_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_gc_limiter_last_enabled_gc_cycle",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "go_gc_pauses_seconds", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_scan_globals_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_scan_heap_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_scan_stack_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_gc_scan_total_bytes", "legendFormat": "{{__name__}}" },
    {
     "expr": "go_gc_stack_starting_size_bytes",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "JDBC监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    { "expr": "jdbc_connections_active", "legendFormat": "{{__name__}}" },
    { "expr": "jdbc_connections_idle", "legendFormat": "{{__name__}}" },
    { "expr": "jdbc_connections_max", "legendFormat": "{{__name__}}" },
    { "expr": "jdbc_connections_min", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "worker监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "dolphinscheduler_worker_full_submit_queue_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_heartbeat_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_overload_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_duration_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_duration_seconds_bucket",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_duration_seconds_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_duration_seconds_max",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_duration_seconds_sum",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_size_bytes",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_size_bytes_bucket",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_size_bytes_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_size_bytes_max",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_worker_resource_download_size_bytes_sum",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "JVM监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    { "expr": "jvm_buffer_count_buffers", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{__name__}}" },
    {
     "expr": "jvm_buffer_total_capacity_bytes",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "jvm_classes_loaded_classes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_classes_unloaded_classes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_gc_memory_allocated_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_gc_memory_promoted_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_gc_pause_seconds", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_gc_pause_seconds_max", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_memory_committed_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_memory_max_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_threads_live_threads", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_threads_peak_threads", "legendFormat": "{{__name__}}" },
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "master监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "dolphinscheduler_master_consume_command_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_master_error_command_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_master_heart_beat_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_master_overload_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_master_task_dispatch_duration_seconds_seconds_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_master_task_dispatch_duration_seconds_seconds_max",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_master_task_dispatch_duration_seconds_seconds_sum",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_master_task_dispatch_error_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ds_master_scheduler_failover_check_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ds_master_scheduler_failover_check_time_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ds_master_scheduler_failover_check_time_seconds_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ds_master_scheduler_failover_check_time_seconds_max",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ds_master_scheduler_failover_check_time_seconds_sum",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ws_stream_master_heart_beat_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ds_master_scheduler_failover_check_time_seconds_bucket",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Tomcat监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "tomcat_sessions_active_max_sessions",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "tomcat_sessions_alive_max_seconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "tomcat_sessions_created_sessions",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "tomcat_sessions_expired_sessions",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "tomcat_sessions_rejected_sessions",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "api监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "dolphinscheduler_api_heartbeat_count_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "prometheus_api_notification_active_subscribers",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "prometheus_api_notification_updates_dropped_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "prometheus_api_notification_updates_sent_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "alert监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "dolphinscheduler_alert_heartbeat_count_total",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "dolphinscheduler_alert_pending", "legendFormat": "{{__name__}}" },
    {
     "expr": "dolphinscheduler_alert_send_count_total",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "dolphinscheduler_alert_sending", "legendFormat": "{{__name__}}" },
    {
     "expr": "dolphinscheduler_alert_usage_duration_seconds_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_alert_usage_duration_seconds_max",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "dolphinscheduler_alert_usage_duration_seconds_sum",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "prometheus_notifications_alertmanagers_discovered",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "守护线程失败的累计次数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 152 },
   "targets": [
    { "expr": "DaemonThreadFail_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "守护线程",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 152 },
   "targets": [
    { "expr": "DaemonThread_total", "legendFormat": "{{name}}" }
   ]
  }
 ]
}